/**
 * RELOAD TOOLS Copyright (c) 2003 Oleg Liber, Bill Olivier, Phillip Beauvoir, Paul Sharples Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use,
 * copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to
 * the following conditions: The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software. THE SOFTWARE
 * IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE
 * AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
 * OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE. Project Management Contact: Oleg Liber Bolton
 * Institute of Higher Education Deane Road Bolton BL3 5AB UK e-mail: o.liber@bolton.ac.uk Technical Contact: Phillip Beauvoir e-mail: p.beauvoir@bolton.ac.uk Paul
 * Sharples e-mail: p.sharples@bolton.ac.uk Web: http://www.reload.ac.uk
 */
package org.olat.lms.scorm.server.beans;

/**
 * The "output" bean - generated by the action class in struts and used to pass information back to the updating hidden frame in the scorm player frameset
 * 
 * @author Paul Sharples
 */
public class LMSResultsBean {

    private final String itemID;
    private final String isSco;
    private final String[][] cmiStrings;
    private final String isUpdating;
    private final String[][] preReqTable;
    private final String isItemCompleted;
    private final String isCourseCompleted;
    private final String hasPrerequisites;

    public LMSResultsBean(final String itemID, final String isSco, final String[][] cmiStrings, final String isUpdating, final String preReqTable[][],
            final String isItemCompleted, final String isCourseCompleted, final String hasPrerequisites) {
        this.itemID = itemID;
        this.isSco = isSco;
        this.cmiStrings = cmiStrings;
        this.isUpdating = isUpdating;
        this.preReqTable = preReqTable;
        this.isItemCompleted = isItemCompleted;
        this.isCourseCompleted = isCourseCompleted;
        this.hasPrerequisites = hasPrerequisites;
    }

    public String getItemID() {
        return (itemID);
    }

    public String getIsSco() {
        return (isSco);
    }

    public String[][] getCmiStrings() {
        return cmiStrings;
    }

    public String getIsUpdating() {
        return isUpdating;
    }

    public String[][] getPreReqTable() {
        return preReqTable;
    }

    public String getIsItemCompleted() {
        return isItemCompleted;
    }

    public String getIsCourseCompleted() {
        return isCourseCompleted;
    }

    public String getHasPrerequisites() {
        return hasPrerequisites;
    }
}
